### ISSUE TITLE
Is this going to have more features?

### ISSUE THREAD

**Issue by buhaytza2005** [0Itsuki0/google-api-rust-client#1]
Hey, not trying to overrun or pressure you into adding features but I was looking for something bare bones to be able to build/add certain things I need at the moment. 
I would need something to pull locations from an account, admins per location, add/remove admins, monitor publisher suggestions etc. 

I came across your crate and it solved my biggest issue - authentication. I have since started writing some code and don't want to just fork and  "make it my own" but at the same time the code is in it's infancy and I can't really pick up on a style.

I would like to add that I am not a well versed Rust developer so may very well be that my code isn't up to your standards but would like to contribute. 

I think I'm just going to create a PR and it can be discussed there if any of my implementations are going against your views for the crate.

Thanks for your work,
Mike

**Comment by 0Itsuki0** [comment]
Hey Mike,
Thank you so much for reaching out!

cannot believe that there are actual people interested in what I am making and really glad that it helps!

To answer your concern, yes, I am indeed planning on adding more features to it!

unfortunately, I am not planning on opening up for contributions at this point in time so it would be great if you could let me know the APIs you need and I will add those next!
( Map API and People API?)

looking forward to hearing back from you. 
Best, 
Itsuki

**Comment by buhaytza2005** [comment]
I would really need the business endpoint, functionality to list/add/remove admins, reviews, replies, publisher suggestions. The project I am trying to get off the ground would manage 200+ locations. 

Would you be happy for me to reuse the auth methods and give credit?

**Comment by 0Itsuki0** [comment]
Yes!
That’s totally fine!
Feel free to do that!

**Comment by buhaytza2005** [comment]
Lovely! 
Thank you very much for your help and hope the crate grows and will be open to contributions in the future! 

Good luck on your project(s)!
